### ISSUE TITLE
Where's your code ?

### ISSUE THREAD

**Issue by muslih14** [smdabdoub/clark-biom#1]
Hi Shareef,
I'm keen to give your CLARK to biom file converter a try out but I can't seem to find your code.

Best wishes,
Muslih.

**Comment by smdabdoub** [comment]
Hi Muslih,
Yes! Thank you! I've been using it myself, but I had completely forgotten to push all the code after initializing the repository.

Everything is up in the repository now, so feel free to install it. I'm still working on getting it uploaded to PyPI, but you can use the install "From GitHub" instructions for now.

Thanks!
